import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { ExternalLink } from "lucide-react";
import localFont from "next/font/local";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <nav className="flex items-center justify-between p-8 mt-2">
            <div className="flex gap-6">
              <Link href="/">Home</Link>
              <Link
                className="items-center flex gap-1"
                href="https://github.com/pytorch/torchtune"
                target="_blank"
              >
                {`torchtune`} <ExternalLink height="12" width="12" />
              </Link>
              <Link
                className="items-center flex gap-1"
                href="https://github.com/vercel/next.js"
                target="_blank"
              >
                {`nextjs`} <ExternalLink height="12" width="12" />
              </Link>
              <Link
                className="items-center flex gap-1"
                href="https://ui.shadcn.com"
                target="_blank"
              >
                {`shadcn/ui`} <ExternalLink height="12" width="12" />
              </Link>
            </div>
            <div className="flex">
              <SignedIn>
                <UserButton />
              </SignedIn>
              <SignedOut>
                <SignInButton>
                  <Link href="/sign-in" className="btn">
                    Sign In / Sign Up
                  </Link>
                </SignInButton>
              </SignedOut>
            </div>
          </nav>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
